version: "3.9"
services:

  spring-api-image:
    image: spring-security-image
    container_name: spring-security-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: securitydb
      MYSQL_USER: raul
      MYSQL_PASSWORD: password1
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume:
