spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:mysql://localhost:3307/securitydb
    username: raul
    password: password1
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret:
    key: e3b1c9f5a7d8e4b9c0f123456789abcd9876543210fedcba1234567890abcdef
  time:
    expiration: 36000 # 1 hour in seconds
