spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
